version: '2.2'
volumes:
  ivideon-server:
services:
  ivideon-server:
    image: frank3427/ivideon
    container_name: ivideon
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'ivideon-server:/root/.IvideonServer/'
    ports:
      - '6080:80'
      - '8081:8080'
      - '3101:3101'
    network_mode: host
    privileged: true
    restart: always
    cpus: "0.20"
    mem_limit: "512M"      
    mem_reservation: "256M"      
